# 示例配置 by Light_Quanta

# 预处理正则关键词
# 在进行实际判断之前，会先将以下正则的内容替换为空，避免使用常见的符号绕过
preprocess: "[+~ 　_\\-\\\\/—.,，。*！!?？@#$%^&()（）=<>；：:;'\"\\[\\]【】{}|·《》`‘“”’]"

# keywords用于定义屏蔽关键词，文本中含有关键词则视为违规
keywords:
#  - 111
#  - 222
#  - 333

# regexKeywords用于定义屏蔽正则表达式，文本匹配正则表达式则视为违规
regex:
#  - ^\d{4}$
#  - ^\d{5}$
#  - ^\d{6}$