name: InteractionSupervisor
version: '${version}'
main: tech.lq0.interactionsupervisor.Main
api-version: '1.16'
authors: [Light_Quanta]
commands:
  interactionsupervisor:
    description: §7[§bI§4S§7]§r §bInteraction§mSupervisor
    usage: §7[§bI§4S§7]§r 用法：/is [reload|ban|unban|banlist|test]
    aliases: is
permissions:
  is.reload:
    description: Reload InteractionSupervisor
    default: op
  is.test:
    description: Test
    default: op
  is.ban:
    description: Ban
    default: op
  is.unban:
    description: Unban
    default: op
  is.banlist:
    description: Banlist
    default: op
  is.delay:
    description: Delay
    default: op
  is.clear:
    description: Clear
    default: op