name: InteractionSupervisor
version: '${version}'
main: tech.lq0.interactionsupervisor.Main
api-version: '1.16'
authors: [Light_Quanta]
commands:
  interactionsupervisor:
    description: §c§l[§bI§mS]§r §bInteraction§mSupervisor
    usage: §c§l[§bI§mS]§r 用法：/is [reload|ban|unban|banlist|test]
    aliases: is
permissions:
  is.reload:
    description: Reload InteractionSupervisor
    default: false
  is.test:
    description: Test
    default: false
  is.ban:
    description: Ban
    default: false
  is.unban:
    description: Unban
    default: false